build-node:
	gev --networkid 15 --datadir /evrynet/data-node/$(node) init /evrynet/data-node/$(node)/genesis.json

start-node-1:
	gev --rpc --networkid 15 --datadir /evrynet/data-node/node1/ console

start-node-2:
	gev --rpc --networkid 15 --datadir /evrynet/data-node/node2/ console

start-node-3:
	gev --rpc --networkid 15 --datadir /evrynet/data-node/node3/ console

start-node-4:
	gev --rpc --networkid 15 --datadir /evrynet/data-node/node4/ console
